version: '3.9'

volumes:
  mysql-vol:

networks:
  app-net:
    driver: bridge

services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - app-net
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - app-net
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
